version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt

formats:
  - pdf

sphinx:
  fail_on_warning: true