version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  test-LiMe:
    docker:
      - image: cimg/python:3.11.9
    steps:
      - checkout
      - run:
          name: Install package + test deps
          command: |
            python -m pip install --upgrade pip setuptools wheel
            # installs your package + pytest/pytest-cov/pytest-mpl from the `tests` extra
            pip install ".[tests]"
      - run:
          name: Run tests and collect coverage
          command: |
            pytest tests --cov --cov-report=xml --mpl
      - codecov/upload

workflows:
  version: 2.1
  build-test:
    jobs:
      - test-LiMe