version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  test-LiMe:
    docker:
      - image: cimg/python:3.10.12
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Run tests and collect coverage
          command: pytest
#         command: pytest --cov ./test
      - codecov/upload

workflows:
  version: 2.1
  build-test:
    jobs:
      - test-LiMe