version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  test-LiMe:
    docker:
      - image: cimg/python:3.11.9   # matches requires-python >=3.11
    steps:
      - checkout

      - run:
          name: Install package + test dependencies
          command: |
            python -m pip install --upgrade pip setuptools wheel
            pip install ".[tests]"   # installs pytest, pytest-cov, pytest-mpl, etc.

      - run:
          name: Run tests and collect coverage
          command: |
            pytest tests --quiet --cov --mpl --cov-report=xml

      - codecov/upload

workflows:
  version: 2.1
  build-test:
    jobs:
      - test-LiMe